/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAAcessoVectorAVar extends PAVar
{
    private TId _id_;
    private PAExp _aExp_;
    private final LinkedList<PAVar> _aVar_ = new LinkedList<PAVar>();

    public AAAcessoVectorAVar()
    {
        // Constructor
    }

    public AAAcessoVectorAVar(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PAExp _aExp_,
        @SuppressWarnings("hiding") List<?> _aVar_)
    {
        // Constructor
        setId(_id_);

        setAExp(_aExp_);

        setAVar(_aVar_);

    }

    @Override
    public Object clone()
    {
        return new AAAcessoVectorAVar(
            cloneNode(this._id_),
            cloneNode(this._aExp_),
            cloneList(this._aVar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAAcessoVectorAVar(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PAExp getAExp()
    {
        return this._aExp_;
    }

    public void setAExp(PAExp node)
    {
        if(this._aExp_ != null)
        {
            this._aExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aExp_ = node;
    }

    public LinkedList<PAVar> getAVar()
    {
        return this._aVar_;
    }

    public void setAVar(List<?> list)
    {
        for(PAVar e : this._aVar_)
        {
            e.parent(null);
        }
        this._aVar_.clear();

        for(Object obj_e : list)
        {
            PAVar e = (PAVar) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aVar_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._aExp_)
            + toString(this._aVar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._aExp_ == child)
        {
            this._aExp_ = null;
            return;
        }

        if(this._aVar_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._aExp_ == oldChild)
        {
            setAExp((PAExp) newChild);
            return;
        }

        for(ListIterator<PAVar> i = this._aVar_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAVar) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
