/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAAnswerValAExp extends PAExp
{
    private TAnswerVal _answerVal_;

    public AAAnswerValAExp()
    {
        // Constructor
    }

    public AAAnswerValAExp(
        @SuppressWarnings("hiding") TAnswerVal _answerVal_)
    {
        // Constructor
        setAnswerVal(_answerVal_);

    }

    @Override
    public Object clone()
    {
        return new AAAnswerValAExp(
            cloneNode(this._answerVal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAAnswerValAExp(this);
    }

    public TAnswerVal getAnswerVal()
    {
        return this._answerVal_;
    }

    public void setAnswerVal(TAnswerVal node)
    {
        if(this._answerVal_ != null)
        {
            this._answerVal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._answerVal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._answerVal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._answerVal_ == child)
        {
            this._answerVal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._answerVal_ == oldChild)
        {
            setAnswerVal((TAnswerVal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
