/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAConstanteADeclaracao extends PADeclaracao
{
    private PADeclaracao _tipo_;
    private PADeclaracao _atribuicaoConst_;
    private TId _id_;

    public AAConstanteADeclaracao()
    {
        // Constructor
    }

    public AAConstanteADeclaracao(
        @SuppressWarnings("hiding") PADeclaracao _tipo_,
        @SuppressWarnings("hiding") PADeclaracao _atribuicaoConst_,
        @SuppressWarnings("hiding") TId _id_)
    {
        // Constructor
        setTipo(_tipo_);

        setAtribuicaoConst(_atribuicaoConst_);

        setId(_id_);

    }

    @Override
    public Object clone()
    {
        return new AAConstanteADeclaracao(
            cloneNode(this._tipo_),
            cloneNode(this._atribuicaoConst_),
            cloneNode(this._id_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAConstanteADeclaracao(this);
    }

    public PADeclaracao getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PADeclaracao node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    public PADeclaracao getAtribuicaoConst()
    {
        return this._atribuicaoConst_;
    }

    public void setAtribuicaoConst(PADeclaracao node)
    {
        if(this._atribuicaoConst_ != null)
        {
            this._atribuicaoConst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atribuicaoConst_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipo_)
            + toString(this._atribuicaoConst_)
            + toString(this._id_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        if(this._atribuicaoConst_ == child)
        {
            this._atribuicaoConst_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipo_ == oldChild)
        {
            setTipo((PADeclaracao) newChild);
            return;
        }

        if(this._atribuicaoConst_ == oldChild)
        {
            setAtribuicaoConst((PADeclaracao) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
