/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAMatrizADeclaracao extends PADeclaracao
{
    private TMatriz _matriz_;
    private PAExp _aExp_;

    public AAMatrizADeclaracao()
    {
        // Constructor
    }

    public AAMatrizADeclaracao(
        @SuppressWarnings("hiding") TMatriz _matriz_,
        @SuppressWarnings("hiding") PAExp _aExp_)
    {
        // Constructor
        setMatriz(_matriz_);

        setAExp(_aExp_);

    }

    @Override
    public Object clone()
    {
        return new AAMatrizADeclaracao(
            cloneNode(this._matriz_),
            cloneNode(this._aExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAMatrizADeclaracao(this);
    }

    public TMatriz getMatriz()
    {
        return this._matriz_;
    }

    public void setMatriz(TMatriz node)
    {
        if(this._matriz_ != null)
        {
            this._matriz_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._matriz_ = node;
    }

    public PAExp getAExp()
    {
        return this._aExp_;
    }

    public void setAExp(PAExp node)
    {
        if(this._aExp_ != null)
        {
            this._aExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._matriz_)
            + toString(this._aExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._matriz_ == child)
        {
            this._matriz_ = null;
            return;
        }

        if(this._aExp_ == child)
        {
            this._aExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._matriz_ == oldChild)
        {
            setMatriz((TMatriz) newChild);
            return;
        }

        if(this._aExp_ == oldChild)
        {
            setAExp((PAExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
