/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AANumberValAExp extends PAExp
{
    private TNumberVal _numberVal_;

    public AANumberValAExp()
    {
        // Constructor
    }

    public AANumberValAExp(
        @SuppressWarnings("hiding") TNumberVal _numberVal_)
    {
        // Constructor
        setNumberVal(_numberVal_);

    }

    @Override
    public Object clone()
    {
        return new AANumberValAExp(
            cloneNode(this._numberVal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAANumberValAExp(this);
    }

    public TNumberVal getNumberVal()
    {
        return this._numberVal_;
    }

    public void setNumberVal(TNumberVal node)
    {
        if(this._numberVal_ != null)
        {
            this._numberVal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numberVal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numberVal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numberVal_ == child)
        {
            this._numberVal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numberVal_ == oldChild)
        {
            setNumberVal((TNumberVal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
