/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AArDeclaracoesADeclaracoes extends PADeclaracoes
{
    private final LinkedList<PADeclaracao> _aDeclaracao_ = new LinkedList<PADeclaracao>();

    public AArDeclaracoesADeclaracoes()
    {
        // Constructor
    }

    public AArDeclaracoesADeclaracoes(
        @SuppressWarnings("hiding") List<?> _aDeclaracao_)
    {
        // Constructor
        setADeclaracao(_aDeclaracao_);

    }

    @Override
    public Object clone()
    {
        return new AArDeclaracoesADeclaracoes(
            cloneList(this._aDeclaracao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArDeclaracoesADeclaracoes(this);
    }

    public LinkedList<PADeclaracao> getADeclaracao()
    {
        return this._aDeclaracao_;
    }

    public void setADeclaracao(List<?> list)
    {
        for(PADeclaracao e : this._aDeclaracao_)
        {
            e.parent(null);
        }
        this._aDeclaracao_.clear();

        for(Object obj_e : list)
        {
            PADeclaracao e = (PADeclaracao) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aDeclaracao_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aDeclaracao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aDeclaracao_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PADeclaracao> i = this._aDeclaracao_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PADeclaracao) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
