/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAShowAComando extends PAComando
{
    private final LinkedList<PAComando> _aComando_ = new LinkedList<PAComando>();
    private PAExp _aExp_;

    public AAShowAComando()
    {
        // Constructor
    }

    public AAShowAComando(
        @SuppressWarnings("hiding") List<?> _aComando_,
        @SuppressWarnings("hiding") PAExp _aExp_)
    {
        // Constructor
        setAComando(_aComando_);

        setAExp(_aExp_);

    }

    @Override
    public Object clone()
    {
        return new AAShowAComando(
            cloneList(this._aComando_),
            cloneNode(this._aExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAShowAComando(this);
    }

    public LinkedList<PAComando> getAComando()
    {
        return this._aComando_;
    }

    public void setAComando(List<?> list)
    {
        for(PAComando e : this._aComando_)
        {
            e.parent(null);
        }
        this._aComando_.clear();

        for(Object obj_e : list)
        {
            PAComando e = (PAComando) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aComando_.add(e);
        }
    }

    public PAExp getAExp()
    {
        return this._aExp_;
    }

    public void setAExp(PAExp node)
    {
        if(this._aExp_ != null)
        {
            this._aExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aComando_)
            + toString(this._aExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aComando_.remove(child))
        {
            return;
        }

        if(this._aExp_ == child)
        {
            this._aExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAComando> i = this._aComando_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAComando) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._aExp_ == oldChild)
        {
            setAExp((PAExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
