/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AASymbolValAExp extends PAExp
{
    private TSymbolVal _symbolVal_;

    public AASymbolValAExp()
    {
        // Constructor
    }

    public AASymbolValAExp(
        @SuppressWarnings("hiding") TSymbolVal _symbolVal_)
    {
        // Constructor
        setSymbolVal(_symbolVal_);

    }

    @Override
    public Object clone()
    {
        return new AASymbolValAExp(
            cloneNode(this._symbolVal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAASymbolValAExp(this);
    }

    public TSymbolVal getSymbolVal()
    {
        return this._symbolVal_;
    }

    public void setSymbolVal(TSymbolVal node)
    {
        if(this._symbolVal_ != null)
        {
            this._symbolVal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._symbolVal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._symbolVal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._symbolVal_ == child)
        {
            this._symbolVal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._symbolVal_ == oldChild)
        {
            setSymbolVal((TSymbolVal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
