/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class TBe extends Token
{
    public TBe()
    {
        super.setText("be");
    }

    public TBe(int line, int pos)
    {
        super.setText("be");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TBe(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBe(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TBe text.");
    }
}
