/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class TIt extends Token
{
    public TIt()
    {
        super.setText("It");
    }

    public TIt(int line, int pos)
    {
        super.setText("It");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIt(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIt(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIt text.");
    }
}
