/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class TIteration extends Token
{
    public TIteration()
    {
        super.setText("iteration");
    }

    public TIteration(int line, int pos)
    {
        super.setText("iteration");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIteration(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIteration(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIteration text.");
    }
}
