/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class TJust extends Token
{
    public TJust()
    {
        super.setText("just");
    }

    public TJust(int line, int pos)
    {
        super.setText("just");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TJust(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTJust(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TJust text.");
    }
}
