/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class TWould extends Token
{
    public TWould()
    {
        super.setText("would");
    }

    public TWould(int line, int pos)
    {
        super.setText("would");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TWould(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTWould(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TWould text.");
    }
}
